# A sample of influencers we used
# these will be used in the scraping scripts
influencers = [
    {"account_name": "drawmyscience", "topics": ["Education"]},
    {"account_name": "khormologia", "topics": ["Education"]},
    {"account_name": "louay.cherni", "topics": ["Education"]},
    {"account_name": "samy.chaffai", "topics": ["Education"]},
    {"account_name": "sahraouiamin", "topics": ["Travel"]},
    {"account_name": "edity.tn", "topics": ["Education"]},
    {"account_name": "nour_momlifestyle", "topics": ["Food"]},
    {"account_name": "learnwithjazzz", "topics": ["Education"]},
    {"account_name": "englishwithjoo", "topics": ["Education"]},
    {"account_name": "ahmed_mak9", "topics": ["Education"]},
    {"account_name": "ahlem.marketing", "topics": ["Education"]},
    {"account_name": "riabi_oussema", "topics": ["Education"]},
    {"account_name": "abir_abdelmalek_", "topics": ["Education"]},
    {"account_name": "amani_invest", "topics": ["Education"]},
    {"account_name": "nader.hellell", "topics": ["Education"]},
    {"account_name": "abitos_wild", "topics": ["Education", "animals"]},
    {"account_name": "lele_wild", "topics": ["Education", "animals"]},
    {"account_name": "animals.interest", "topics": ["Education", "animals"]},
    {"account_name": "lacompagniedesanimaux ", "topics": ["Education", "animals"]},
    {"account_name": "epicurieuxanimaux ", "topics": ["Education", "animals"]},
    {"account_name": "lafermedesanimaux", "topics": ["Education", "animals"]},

    {"account_name": "abtal_industry", "topics": ["Sports", "Education"]},
    {"account_name": "haroun_louati", "topics": ["Travel"]},
    {"account_name": "firaselechi", "topics": ["Education"]},
    {"account_name": "nesrine_lylia", "topics": ["Food"]},
    {"account_name": "safatelli7", "topics": ["Food"]},
    {"account_name": "thechrissyhazel", "topics": ["Travel"]},
    {"account_name": "amine.abdennour1", "topics": ["Education"]},
    {"account_name": "lakrim_attouchi", "topics": ["Education"]},
    {"account_name": "yasser_machat", "topics": ["Education"]},
    {"account_name": "aniiskallel", "topics": ["Education"]},
    {"account_name": "mannai.oucef", "topics": ["Education"]},
    {"account_name": "nader.hellell", "topics": ["Education"]},






    #{"account_name": "kifehglenza", "topics": ["Education", "Sports"]},
    {"account_name": "aziz_jedidi", "topics": ["Education"]},
    {"account_name": "mys_journey", "topics": ["Sports"]},
    {"account_name": "coach_oussama_trabelsi", "topics": ["Sports"]},
    {"account_name": "enji_maaroufi_", "topics": ["Music"]},
    {"account_name": "go.rihab", "topics": ["Travel"]},
    {"account_name": "khoubaib_jebabli", "topics": ["Education"]},
    {"account_name": "mezianedahou", "topics": ["Education"]},
    {"account_name": "khaliltrabelsi", "topics": ["Education"]},
    {"account_name": "med_mouhib_meddeb", "topics": ["Education"]},
    {"account_name": "dr._olfa", "topics": ["doctor"]},
    {"account_name": "mahdisouab1", "topics": ["Education"]},
    {"account_name": "ameen_hamrouni", "topics": ["Education"]},
    {"account_name": "louissimalek41", "topics": ["Education"]},
    {"account_name": "alyahakimofficiel", "topics": ["Education"]},
    {"account_name": "itsbahahaouas", "topics": ["Education"]},
    {"account_name": "firas_bahrini_officiel", "topics": ["Fashion"]},
    {"account_name": "nader_khlif", "topics": ["Sports","Food"]},
    {"account_name": "cours.elysee", "topics": ["thevmaker"]},
    {"account_name": "cours.elysee", "topics": ["Education"]},
    {"account_name": "rayen_bouajaja", "topics": ["Education"]},
    {"account_name": "maramnahass", "topics": ["Fashion", "Food", "Travel"]},
    {"account_name": "faccna.tn", "topics": ["Education"]},
    {"account_name": "wajd_chelly", "topics": ["Food", "Lifestyle"]},
    {"account_name": "doctor.karim.mechri", "topics": ["Doctor"]},
    {"account_name": "laajimiahmed", "topics": ["Acting"]},
        {"account_name": "laajimiahmed", "topics": ["Acting"]},
    {"account_name": "bachtarzimehdi", "topics": ["Acting"]},
    {"account_name": "nour.saidi_", "topics": ["Acting"]},
    {"account_name": "loujey", "topics": ["Acting"]},
    {"account_name": "laajimiahmed", "topics": ["Acting"]},
    {"account_name": "hamdi_hadda", "topics": ["Acting"]},
    {"account_name": "mustafa_houas", "topics": ["Acting"]},
    {"account_name": "lotfiabdelli", "topics": ["Acting"]},
    {"account_name": "marwenebouzayene", "topics": ["Acting"]},
    {"account_name": "walid_bouheni", "topics": ["Acting"]},
    {"account_name": "amine.limemmm", "topics": ["Acting"]},
    {"account_name": "abdeddayem.fares", "topics": ["Acting", "Fashion"]},
    {"account_name": "bentaher_dali", "topics": ["Music"]},
    {"account_name": "tarek__baalouch", "topics": ["Acting"]},
    {"account_name": "amen_moussa", "topics": ["Acting"]},
    {"account_name": "jun_garza", "topics": ["Acting"]},
    {"account_name": "gharbiikarim", "topics": ["Acting"]},
    {"account_name": "med_ali_tounsi", "topics": ["Acting"]},
    {"account_name": "nejibbelkadhi", "topics": ["Acting"]},
    {"account_name": "kamel_touati_officiel", "topics": ["Acting"]},
    {"account_name": "zynemastouri", "topics": ["Acting"]},
    {"account_name": "bassoum_hamraoui", "topics": ["Acting"]},
    {"account_name": "dali_benjemaa", "topics": ["Acting"]},
    {"account_name": "fethi.haddaoui", "topics": ["Acting"]},
    {"account_name": "medmrad_official", "topics": ["Acting"]},
    {"account_name": "nejibbelkadhi", "topics": ["Acting"]},
    {"account_name": "nidhal.saadi.officiel", "topics": ["Acting"]},
    {"account_name": "yassinebengamra", "topics": ["Acting"]},
    {"account_name": "oumaymabenhafsia4", "topics": ["Acting"]},
    {"account_name": "rymriahi", "topics": ["Acting"]},
    {"account_name": "sadokhalwess", "topics": ["Acting"]},
    {"account_name": "nassimbourguiba", "topics": ["Acting"]},
    {"account_name": "asma_ben.othmane", "topics": ["Acting"]},
    {"account_name": "nahdi.dali.officiel", "topics": ["Acting"]},
    {"account_name": "jamilachihi", "topics": ["Acting"]},
    {"account_name": "dhaferlabidine", "topics": ["Acting"]},
    {"account_name": "ziedtouatiofficial", "topics": ["Acting"]},
    {"account_name": "jebaliaziz", "topics": ["Acting"]},
    {"account_name": "chedlyarfaoui", "topics": ["Acting"]},
    {"account_name": "yasminadimassi", "topics": ["Acting"]},
    {"account_name": "hella.ayed", "topics": ["Acting"]},
    {"account_name": "amirachebli", "topics": ["Acting"]},
    {"account_name": "wahida.dridi.officiel", "topics": ["Acting"]},
    {"account_name": "chekra_rammeh", "topics": ["Acting"]},
    {"account_name": "hanen_chograni_", "topics": ["Acting"]},
    {"account_name": "ahmed_landolsi", "topics": ["Acting"]},
    {"account_name": "khaoulaslimaniofficial", "topics": ["Acting", "Fashion"]},
    {"account_name": "hafiene_ahmed", "topics": ["Acting"]},
    {"account_name": "najlabenabdallah.official", "topics": ["Acting", "Fashion"]},
    {"account_name": "salma_mahjoubi_officiel", "topics": ["Acting", "Fashion"]},
    {"account_name": "souhir_ben_amara", "topics": ["Acting", "Fashion"]},
    {"account_name": "raouf_ben_amor", "topics": ["Acting"]},
    {"account_name": "bilel.briki.officiel", "topics": ["Acting"]},
    {"account_name": "aichabahmed", "topics": ["Acting","Fashion"]},
    {"account_name": "samiatrabelsiii", "topics": ["Acting","Fashion"]},
    {"account_name": "samiramagroun", "topics": ["Acting","Fashion"]},
    {"account_name": "helmi.dridi.official", "topics": ["Acting"]},
    {"account_name": "hakim_boumsaoudi_officiel", "topics": ["Acting"]},
    {"account_name": "khaledhouissa", "topics": ["Acting"]},
    {"account_name": "nadiaboussettaoff", "topics": ["Acting"]},
    {"account_name": "raouf_ben_amor", "topics": ["Acting"]},
    {"account_name": "majdi.smiri", "topics": ["Acting"]},
    {"account_name": "hichem_rostom_officiel", "topics": ["Acting"]},
    {"account_name": "kaouther.bel.haj", "topics": ["Acting"]},
    {"account_name": "ajenguimoncef", "topics": ["Acting"]},
    {"account_name": "raniagabsi", "topics": ["Acting", "Fashion"]},
    {"account_name": "aminebensalah__", "topics": ["Acting"]},
    {"account_name": "rahalibahri", "topics": ["Acting"]},
    {"account_name": "sondos_belhassen", "topics": ["Acting"]},
    {"account_name": "jihed_chernii", "topics": ["Acting"]},
    {"account_name": "bilel.slatnia", "topics": ["Acting"]},
    {"account_name": "hendsabri", "topics": ["Acting", "Fashion"]},
    {"account_name": "coach_aidi_ghaith", "topics": ["Sports"]},
    {"account_name": "talk.tunisia", "topics": ["Education", "Food"]},
    {"account_name": "mohamed.dahech_officiel", "topics": ["Acting"]},
    {"account_name": "samehsankari", "topics": ["Acting"]},
    {"account_name": "malek.ben.saad", "topics": ["Acting"]},
    {"account_name": "majdmastoura", "topics": ["Acting"]},
























    {"account_name": "lyceena.tn", "topics": ["Education"]},
    {"account_name": "issra.jr", "topics": ["Education"]},
    {"account_name": "rivezlitn", "topics": ["Education"]},
    {"account_name": "ayoub.meftah.71", "topics": ["Education"]},
    {"account_name": "hakimvoice", "topics": ["Education"]},
    {"account_name": "rawaa.aljallad", "topics": ["Education"]},
    {"account_name": "islam.zrelli", "topics": ["Education"]},
    {"account_name": "khalil.tarhouni", "topics": ["Education"]},
    {"account_name": "nourchenne_cheguenni", "topics": ["Doctor"]},
    {"account_name": "khaoula_tunnipon", "topics": ["Education"]},
    {"account_name": "rahalista", "topics": ["Travel"]},
    {"account_name": "aymennasri", "topics": ["Education"]},
    {"account_name": "arjoun.noor", "topics": ["Music"]},
    {"account_name": "yaluna_magazine", "topics": ["Education"]},
    {"account_name": "aymennasri", "topics": ["Education"]},
    {"account_name": "aymennasri", "topics": ["Education"]},
    {"account_name": "aymennasri", "topics": ["Education"]},



    {"account_name": "roukatravel", "topics": ["Travel"]},
    {"account_name": "sahar_brinis", "topics": ["Travel"]},
    {"account_name": "le_couple_bougeotte", "topics": ["Travel"]},
    {"account_name": "wantotrip", "topics": ["Travel"]},
    {"account_name": "jihed_mhb", "topics": ["Travel"]},
    {"account_name": "kbaier_the_adventurer", "topics": ["Travel"]},
    {"account_name": "this_is_tunisia__", "topics": ["Travel"]},
    {"account_name": "adem_djerba_tourism", "topics": ["Travel"]},
    {"account_name": "avaloon.tunisia", "topics": ["Travel"]},
    {"account_name": "master_of_camping", "topics": ["Travel"]},
    {"account_name": "elhelma_camping", "topics": ["Travel"]},
    {"account_name": "monsieur.voyagee", "topics": ["Travel"]},
    {"account_name": "camsoutravel", "topics": ["Travel"]},
    {"account_name": "20camels", "topics": ["Travel"]},
    {"account_name": "escapadeqatar", "topics": ["Travel"]},
    {"account_name": "yalla_adventure_jo", "topics": ["Travel"]},
    {"account_name": "travelwithrahma", "topics": ["Travel"]},
    {"account_name": "travel_with_zoubair", "topics": ["Travel", "Education"]},
    {"account_name": "travel_with_food_by_hind", "topics": ["Travel", "Food"]},
    {"account_name": "traveleriste", "topics": ["Travel"]},
    {"account_name": "dr.voysci", "topics": ["Travel", "Health"]},
    {"account_name": "rahmatraveler", "topics": ["Travel"]},
    {"account_name": "with_thesmile", "topics": ["Travel"]},
    {"account_name": "discoverwithnada", "topics": ["Travel"]},
    {"account_name": "je.teste.for.you", "topics": ["Food"]},
    {"account_name": "tunisian_discoverer", "topics": ["Travel"]},
    {"account_name": "amine.adventurer", "topics": ["Travel"]},
    {"account_name": "ahmed_masmoudi_26", "topics": ["Travel"]},
    {"account_name": "theadventurerwithin", "topics": ["Travel"]},
    {"account_name": "campingtestour", "topics": ["Travel"]},
    {"account_name": "travelwithadamk", "topics": ["Travel"]},
    {"account_name": "daminobenhamza", "topics": ["Travel"]},
    {"account_name": "tunisia.with.my.eyes", "topics": ["Travel"]},

]